"""
Simple test to verify tool calling functionality.

This script tests:
1. Tool calls are generated by the model
2. Tool calls are executed
3. Tool results are returned
4. Agent uses tool results in response
"""

import asyncio
from pydantic_ai import Agent, ModelSettings
from app.models import finance_model


# Simple tool for testing
def add_numbers(a: float, b: float) -> str:
    """Adds two numbers together.
    
    Args:
        a: First number
        b: Second number
    
    Returns:
        Sum of a and b as a string
    """
    result = a + b
    return f"The sum of {a} and {b} is {result}"


def multiply_numbers(a: float, b: float) -> str:
    """Multiplies two numbers together.
    
    Args:
        a: First number
        b: Second number
    
    Returns:
        Product of a and b as a string
    """
    result = a * b
    return f"The product of {a} and {b} is {result}"


# Create a simple agent with tools
test_agent = Agent(
    finance_model,
    model_settings=ModelSettings(max_output_tokens=500),
    system_prompt=(
        "You are a helpful assistant that uses tools to perform calculations. "
        "When asked to perform a calculation, you MUST use the available tools. "
        "Always use the tools for any mathematical operations."
    ),
    tools=[add_numbers, multiply_numbers],
)


async def test_tool_call_detection():
    """Test 1: Verify tool calls are generated."""
    print("=" * 60)
    print("TEST 1: Tool Call Detection")
    print("=" * 60)
    
    question = "What is 15 plus 27? Use the add_numbers tool."
    
    print(f"Question: {question}\n")
    
    result = await test_agent.run(question)
    
    print(f"Response: {result.output}\n")
    
    # Check for tool calls
    tool_calls_detected = False
    tool_calls_count = 0
    
    if hasattr(result, 'all_messages'):
        try:
            messages = list(result.all_messages())
            for msg in messages:
                if hasattr(msg, 'tool_calls') and msg.tool_calls:
                    tool_calls_detected = True
                    tool_calls_count = len(msg.tool_calls)
                    print(f"✅ Tool calls detected: {tool_calls_count}")
                    for i, tc in enumerate(msg.tool_calls, 1):
                        if hasattr(tc, 'function') and hasattr(tc.function, 'name'):
                            tool_name = tc.function.name
                            args = getattr(tc.function, 'arguments', {})
                            print(f"  {i}. Tool: {tool_name}")
                            print(f"     Arguments: {args}")
        except Exception as e:
            print(f"❌ Error inspecting messages: {e}")
    
    if not tool_calls_detected:
        print("❌ NO TOOL CALLS DETECTED")
        print("   The model did not generate tool calls.")
    
    print()


async def test_tool_execution():
    """Test 2: Verify tools are executed and results are used."""
    print("=" * 60)
    print("TEST 2: Tool Execution and Results")
    print("=" * 60)
    
    question = "Multiply 8 by 9 using the multiply_numbers tool."
    
    print(f"Question: {question}\n")
    
    result = await test_agent.run(question)
    
    print(f"Response: {result.output}\n")
    
    # Check if tool was called and result is in response
    tool_called = False
    tool_result_in_response = False
    
    if hasattr(result, 'all_messages'):
        try:
            messages = list(result.all_messages())
            for msg in messages:
                if hasattr(msg, 'tool_calls') and msg.tool_calls:
                    tool_called = True
                    for tc in msg.tool_calls:
                        if hasattr(tc, 'function'):
                            tool_name = tc.function.name
                            print(f"✅ Tool called: {tool_name}")
                            
                            # Check if tool result is in the response
                            if hasattr(tc, 'result') or hasattr(tc, 'tool_result'):
                                result_text = str(getattr(tc, 'result', None) or getattr(tc, 'tool_result', None))
                                if result_text and result_text in result.output:
                                    tool_result_in_response = True
                                    print(f"✅ Tool result found in response")
        except Exception as e:
            print(f"❌ Error: {e}")
    
    if not tool_called:
        print("❌ Tool was not called")
    if not tool_result_in_response:
        print("⚠️  Tool result may not be in response (check manually)")
    
    print()


async def test_multiple_tools():
    """Test 3: Verify multiple tool calls work."""
    print("=" * 60)
    print("TEST 3: Multiple Tool Calls")
    print("=" * 60)
    
    question = "First add 10 and 20, then multiply the result by 3."
    
    print(f"Question: {question}\n")
    
    result = await test_agent.run(question)
    
    print(f"Response: {result.output}\n")
    
    # Count tool calls
    tool_calls_count = 0
    tools_used = []
    
    if hasattr(result, 'all_messages'):
        try:
            messages = list(result.all_messages())
            for msg in messages:
                if hasattr(msg, 'tool_calls') and msg.tool_calls:
                    tool_calls_count += len(msg.tool_calls)
                    for tc in msg.tool_calls:
                        if hasattr(tc, 'function') and hasattr(tc.function, 'name'):
                            tools_used.append(tc.function.name)
        except Exception as e:
            print(f"❌ Error: {e}")
    
    print(f"Tool calls made: {tool_calls_count}")
    if tools_used:
        print(f"Tools used: {', '.join(tools_used)}")
    
    if tool_calls_count >= 2:
        print("✅ Multiple tool calls detected")
    else:
        print("⚠️  Expected multiple tool calls")
    
    print()


def calculer_valeur_future(
    capital_initial: float,
    taux_annuel: float,
    duree_annees: float
) -> str:
    """Calcule la valeur future avec intérêts composés.
    
    Args:
        capital_initial: Montant initial en euros
        taux_annuel: Taux d'intérêt annuel (ex: 0.05 pour 5%)
        duree_annees: Durée en années
    
    Returns:
        Valeur future calculée
    """
    valeur_future = capital_initial * (1 + taux_annuel) ** duree_annees
    interets = valeur_future - capital_initial
    return (
        f"Valeur future: {valeur_future:,.2f}€\n"
        f"Intérêts générés: {interets:,.2f}€\n"
        f"Capital initial: {capital_initial:,.2f}€"
    )


async def test_financial_tool():
    """Test 4: Test with actual financial tool."""
    print("=" * 60)
    print("TEST 4: Financial Tool")
    print("=" * 60)
    
    financial_agent = Agent(
        finance_model,
        model_settings=ModelSettings(max_output_tokens=500),
        system_prompt=(
            "You are a financial advisor. Use the calculer_valeur_future tool "
            "for all future value calculations. DO NOT calculate manually."
        ),
        tools=[calculer_valeur_future],
    )
    
    question = "Calculate the future value of 10000€ at 5% for 5 years."
    
    print(f"Question: {question}\n")
    
    result = await financial_agent.run(question)
    
    print(f"Response: {result.output}\n")
    
    # Check for tool call
    tool_called = False
    tool_calls_count = 0
    if hasattr(result, 'all_messages'):
        try:
            messages = list(result.all_messages())
            for msg in messages:
                if hasattr(msg, 'tool_calls') and msg.tool_calls:
                    tool_called = True
                    tool_calls_count = len(msg.tool_calls)
                    print(f"✅ Tool calls detected: {tool_calls_count}")
                    for i, tc in enumerate(msg.tool_calls, 1):
                        if hasattr(tc, 'function') and hasattr(tc.function, 'name'):
                            print(f"  {i}. Tool: {tc.function.name}")
                            args = getattr(tc.function, 'arguments', {})
                            if args:
                                print(f"     Arguments: {args}")
                            # Check for tool result
                            if hasattr(tc, 'result'):
                                result_text = str(tc.result)
                                print(f"     Result: {result_text[:100]}...")
        except Exception as e:
            print(f"❌ Error: {e}")
    
    if not tool_called:
        print("❌ Financial tool was not called")
    else:
        print(f"✅ Financial tool successfully called and executed")
    
    print()


async def main():
    """Run all tests."""
    print("\n" + "=" * 60)
    print("TOOL CALLING VERIFICATION TESTS")
    print("=" * 60 + "\n")
    
    await test_tool_call_detection()
    await test_tool_execution()
    await test_multiple_tools()
    await test_financial_tool()
    
    print("=" * 60)
    print("TESTS COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())

